FROM php:7.1.33-fpm

COPY ./docker/php/php.ini /usr/local/etc/php/

# 本番環境の場合はファイルをコピーする必要がある
COPY . /var/www
COPY ./.env_prod /var/www/.env

WORKDIR /var/www

RUN apt-get update \
  && apt-get install -y zlib1g-dev mariadb-client unzip \
  && docker-php-ext-install zip pdo_mysql
  && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer \
  && composer install
  && chmod -R a+w storage/ bootstrap/cache
